In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score 
import numpy as np
import pandas as pd


In [2]:
ds = datasets.load_iris()
X = ds.data
y = ds.target
y_name = ds.target_names


In [3]:
print(X[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [4]:
X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size=0.2,
                                                    random_state=123,
                                                    stratify=y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape )

(120, 4) (30, 4) (120,) (30,)


### SVC

In [5]:
from sklearn.svm import SVC

X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size=0.2,
                                                    random_state=123,
                                                    stratify=y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape )
svm_clf = SVC()
svm_clf.fit(X_train, y_train)
acc = accuracy_score(y_test, svm_clf.predict(X_test))
print(acc)

(120, 4) (30, 4) (120,) (30,)
0.9


### KNN

In [6]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size=0.2,
                                                    random_state=123,
                                                    stratify=y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape )
knn_clf = KNeighborsClassifier()
knn_clf.fit(X_train, y_train)
acc = accuracy_score(y_test, knn_clf.predict(X_test))
print(acc)

(120, 4) (30, 4) (120,) (30,)
0.9333333333333333


### RandomForest

In [7]:
from sklearn.ensemble import RandomForestClassifier
X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size=0.2,
                                                    random_state=123,
                                                    stratify=y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape )

rf_clf = RandomForestClassifier()
rf_clf.fit(X_train, y_train)
acc = accuracy_score(y_test, rf_clf.predict(X_test))
print(acc)

(120, 4) (30, 4) (120,) (30,)
0.9666666666666667


In [8]:
import joblib

joblib.dump(svm_clf, "svm_clf.joblib")
joblib.dump(knn_clf, "knn_clf.joblib")
joblib.dump(rf_clf, "rf_clf.joblib")

['rf_clf.joblib']

In [9]:
import joblib

# 假設你已經成功建立了 knn_clf 模型



# 載入 knn_clf 模型
loaded_knn_clf = joblib.load('knn_clf.joblib')

# 確認模型是否相同
if str(knn_clf) == str(loaded_knn_clf):
    print("模型成功儲存並載入。")
else:
    print("模型儲存或載入時出現問題。")


模型成功儲存並載入。
